# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Felix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Felix
  pod 'SnapSDK'
  pod 'Charts'

  target 'FelixTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FelixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
